README.md

[Docs] 리드미 수정 테스트

---

README.md

- 잔디 심기가 잘 되는지 리드미 수정 테스트 2차
- X

[Docs] 리드미 수정 테스트 2

---

src/hwp_to_pdf.py

- src/hwp_to_pdf.py 예외 처리 보강 및 함수별 docstring 추가
- 없음

[Refactor] 방어적 예외 처리 및 문서화 개선

---

src/hwp_to_pdf.py

[Style] 함수 타입 및 Docstring 추가

---

src/pdf_loader.py

PDF 파일의 문서 내용을 긁어오는 코드 추가
pip install easyocr PyMuPDF numpy pandas pillow tqdm
위와 같은 라이브러리 필요

[FEAT] PDF 로더 코드 추가

---

src/data_load.py
src/pdf_loader.py

[Feat] data_load 함수에 pdf도 함께 처리하도록 추가

---

src/data_load.py

파일 타입으로 hwp / pdf / all 을 받아서 해당 확장자인 파일만 처리하도록 바꿈
all 이 아니라 hwp/pdf 일떄는 맞지 않는 확장자 파일을 아예 데이터 프레임에서 필터링 함

[Feat] data_process 함수에 file_type 인자 추가

---

config.yaml

config.yaml 파일 내부의 query 부분의 query를 text로 변환함
- 내용

[Fix] config.yaml 파일 query 부분 query > text 로 고침

---

config.yaml
main.py
src/data_loader.py
src/vector_db.py

- data_list에서 문서를 불러올 때 숫자 제한 기능 추가했습니다.
- 청크의 splitter 분기를 추가했고 config에 적용했습니다.
- data_load.py -> data_loader.py로 변경되었습니다

[Feat] data_loader.py 문서제한기능, 청크 splitter 분기 추가, main.py 및 config.yaml 변경

---

.gitignore
src/data_loader.py

- 텍스트 기본 정제 기능 추가, data_chunking 모듈에서 모든 chunk진행전 raw text에 정제 진행
- N/A

[Fix] 브랜치 commit 이상 발생, 재생성

---

.gitignore

- .gitignore 수정
- vector_db저장 파일 예외처리
- N/A

[Fix] .gitignore vector_db 예외처리

---

main.py
src/data_loader.py

- 방어적 코드 형식을 추가했습니다. 자세한 사항은 github/코드형식을 참고해주세요
- 내용

[Style] 방어적 코드 형식 통일

---

src/data_loader.py

[Fix] 코드 에러 수정

---

src/vector_db.py

[Style] vector_db.py 방어적 코드 형식 통일

---

config.yaml
main.py

- 메인에서 벡터DB 생성 또는 로드 분기 추가
- 내용

[Feat&Fix] 메인에서 벡터DB 생성 또는 로드 분기 추가

---

config.yaml
main.py
src/vector_db.py

- 벡터디비 저장 이름을 동적으로 할당
- 아직 FAISS만 기능하므로 이후에 추가 필요 및 이름 동적할당도 맞춰서 변경해야함

[Feat] 벡터디비 저장시 이름을 동적으로 할당

---

config.yaml
src/utils/config.py

- config.yaml에서 사용하지 않는 것들을 모두 삭제했습니다. 컨피그를 불러올때는 config.py를 이용해주세요
- 내용

[Refactor] config통일 및 방어적 코딩 구현

---

config.yaml
src/utils/config.py

[Fix] load_config실행확인

---

src/utils/config.py

[Feat] verbose 출력물 추가

---

config.yaml
embed_test.py
main.py
retrieval_test.py
src/embedding/embedding_main.py
src/retrieval/retrieval.py
src/retrieval/retrieval_main.py

- retrieval_test.py를 생성했습니다.
- retrieval_test.py를 반영하여 retrieval_main.py도 함께 수정했습니다.
- retrieval에서 사용하고 있던 all_chunks 변수명을 chunks로 전부 통일시켰습니다.
- embedding_main.py에서 embed_config.get("model", "openai")로 불러오는 부분이 변수명 불일치로 오류가 발생했습니다. 따라서 ("embed_model", "openai")로 수정했습니다.
- X

[Feat] retrieval_test.py 생성

---

config.yaml

-  config.yaml의 search_type에 주석으로 hybrid 선택지를 추가했습니다.
- X

[Fix] search_type에 주석으로 선택지 추가

---

src/retrieval/retrieval.py
src/retrieval/retrieval_main.py

[Fix] 리트리버 반환 형식 수정

---

embed_test.py
src/embedding/embedding_main.py
src/embedding/vector_db.py

- python embed_test.py --is_save
- save 모드 추가, argparser로 구현. 
- 지정 query에 대한 chunk 생성 후 retrieval, generator실험 시 추가 적인 chunk 계산이 없도록 load시에는 추가적인 청크 계산없이 저장된 db 로드.
- argparser로 구현된 것을 염두에 두어 query 변경시
- python embed_test.py --is_save 로 vector_db를 최신화 하는 것을 잊지 말자!

[Feat] vector_db 생성 및 로드 방식 변경

---

config.yaml
src/retrieval/retrieval.py
src/retrieval/retrieval_main.py
src/utils/config.py

- Retrieval 관련 디버깅 코드, 예외 처리 추가했습니다.
- X

[Fix] Retrieval 디버깅 코드, 예외 처리 추가

---

src/loader/data_loader.py
src/loader/loader_main.py

- 캐쉬가 늘어나는 것을 방지하고자 임베딩 모델을 통일해서 적용할 수 있도록 만들었습니다.
- pip install tabulate가 필요합니다 주의해주세요

[Fix] loader에서 문서유사도 검색을 위해 사용하는 임베딩 모델을 embedding과 통일

---

README.md

- streamlit 사용법 및 이용 시 알아두면 좋을 점 추가

[Update] streamlit에 관하여 README.md 수정

---

generator_test.py
retrieval_test.py
src/loader/data_loader.py

- python embed_test.py --is_save 에 맞춰서 리트리버 제너레이터도 수정함
- 내용

[Fix] embedding 업데이트에 따른 리트리버 제네레이터 테스트 모듈 변경

---

config.yaml
src/loader/loader_main.py
src/loader/splitter.py

section+recursive -> section으로 이름 변경

[Fix] section+recursive -> section으로 이름 변경

---

app.py
config.yaml
retrieval_test.py
src/embedding/embedding_main.py
src/loader/data_loader.py
src/retrieval/retrieval.py

- streamlit UI 변경, 설정 변경 할 때 마다 검색되는 부분을 수정.
- key를 "user_query"로 설정하면, 랜더링 진행 중 변경이 불가능한 것을 확인
- key값일 갱신될수있도록 변경하여 매 검색마다 input_key_version을 증가 시키는 것으로 query 초기화를 가능하게 만듬
- 검색 버튼을 만드는 것으로, 검색버튼을 누르지 않는한 검색이 시작되지 않도록 설정하여, 설정 변경을 자유롭게 할수있도록 수정

[Fix] Streamlit UI 변경

---

src/loader/splitter.py

주석처리 한 출력물 verbose=False로 끌 수 있게 변경

[Fix] 주석처리 한 출력물 verbose=False로 끌 수 있게 변경

---

app.py

[Feat] app.py Generator 기능 추가

---

src/retrieval/retrieval.py
src/retrieval/retrieval_main.py

- 리트리버이후 리랭크의 최대최소 청크를 보장하는 기능 추가
- 내용

[Fix] 리트리버 리랭크이후 최대최소 청크 보장 기능 구현

---

README.md
src/loader/splitter.py

- [Fix] Readme.md 폴더구조 및 구현된 기능 정리
- 내용

[Fix] Readme.md 폴더구조 및 구현된 기능 정리

---

embed_test.py
generator_test.py
loader_test.py
main.py
retrieval_test.py

- 메인과 테스트 파일 로깅을 구현했습니다.
- 왜인지 로더와 임베딩 테스트 파일은 로깅이 안되는데 이후 수정하겠습니다.
- 내용

[Feat] 메인 및 테스트 파일 로깅 기능 구현

---

app.py

- 변경된 config를 반영 하여, app.py에서 불러오는 인자 수정

[Update] 변경된 config를 반영 하여, app.py에서 불러오는 인자 수정

---

embed_test.py
generator_test.py
loader_test.py
main.py
retrieval_test.py
src/retrieval/retrieval.py
src/retrieval/retrieval_main.py

- 공유 캐시 해결 함수를 전체 실행 파일에 추가
- X

[Feat] 공유 캐시 해결 함수 호출 전체 설정

---

app.py

- streamlit app.py 에서 히스토리 저장을 하되 출력 및 초기화가 안되는 부분 수정.

[Feat] 히스토리 저장 및 출력, 히스토리 초기화 조건 추가

---

src/streamlit/chatbot.py

[Fix] min_chunk -> rerank_top_k 수정

[Fix] min_chunk -> rerank_top_k 수정

---

app.py

[FIx] app.py 현황 업데이트

---

app/main.py
fastapi/main.py
fastapi/rag_api.py
rag_api.py

[Feat] Fast API 관련 코드 추가

---

src/streamlit/chatbot.py

- chatbot 사이드바 extender에 추출된 문서를 볼수있는 옵션 구현
- retriever 에서 추출된 문서를 state로 남겨 동적으로 반영될 수 있게 구현.

[Feat] chatbot 사이드바 extender를 이용한 추출된 문서 보기

---

src/streamlit/chatbot.py

- chatbot 히스토리 정리 기능 추가
- chat history 및 참고 문서 내역 정리
- 참고 문서 추출된 내역을 보여주던 사이드바에서 내역이 자동 업데이트가 안되고 수동으로 사이드바를 옮겨야지만 업데이트된 내역을 확인할수 있던것을 자동 업데이트 되게 변경
- 내용

[Feat & Fix] 히스토리 정리 및 페이지 자동 업데이트 기능 추가

---

src/generator/generator_main.py
src/generator/make_prompt.py
src/loader/data_loader.py
src/loader/loader_main.py
src/retrieval/retrieval.py
src/retrieval/retrieval_main.py
src/streamlit/chatbot.py

…함수 생성
[Feat, Fix] 유사도 문서 검색, retrieval에 chat_history 반영, load_chat_history 함수 생성
유사도 문서 검색 파트에서 잘 기능하는 것 같지 않음 -> 보완 필요

[Feat, Fix] 유사도 문서 검색, retrieval에 chat_history 반영, load_chat_history 함수 생성

---

.gitignore

[Update] 노트북 파일 참조 금지 .gitignore 수정

---

src/generator/hf_generator.py
src/generator/make_prompt.py

- 의미없는 프롬프트구절과 stopwords 수정
- 내용

[Fix] 의미없는 프롬프트구절과 stopwords 수정

---

src/streamlit/chatbot.py

[Fix] 변수명, 중복 출력 등 문제 해결

---

src/streamlit/chatbot.py

- chatbot.py의 229번째 줄 코드의 python 따옴표 문법 오류 수정
- X

[Fix] python 따옴표 문법 오류 수정

---

main.py

- [Fix] main.py 컨피그 함수 수정에 따른 변경
- 내용

[Fix] main.py 컨피그 함수 수정에 따른 변경

---

src/loader/splitter.py

[Refactor] splitter.py 리팩토링

---

embed_test.py
generator_test.py
loader_test.py
main.py
retrieval_test.py
src/retrieval/retrieval.py
src/retrieval/retrieval_main.py
src/utils/config.py
src/utils/shared_cache.py

- 메인 및 테스트에서 작동하는지 확읺하는 TODO 리스트 추가
- 내용

[Refactor] 메인 및 테스트에서 작동하는지 확읺하는 TODO 리스트 추가

---

embed_test.py
retrieval_test.py

[Refactor] 리펙토링된 임베딩에 맞게 리트리버 테스트 파일 변경

---

src/embedding/embedding_main.py

- embedding_main 내의 config에 관한 방어적 코드 삭제
- 내용

[Refactor] embedding_main 내의 config 검사 삭제

---

main.py
src/streamlit/chatbot.py

- embedding, chat_history 인자 추가
- streamlit 구동 확인
- config 변경사항 출력 확인
- chat history 반영 시 오류가 일어나는 부분이 생김

[Fix] 인자 수정, chatbot 구동 확인

---

main.py
src/loader/loader_main.py

[Fix] loader_main에서 config와 chat_history 중복 사용 수정

[Fix] loader_main에서 config와 chat_history 중복 사용 수정

---

main.py
src/loader/data_loader.py
src/loader/loader_main.py

[Refactor] 로더 코드 수정

---

src/streamlit/chatbot.py

- chatbot.py 에 load_chat_history 수정
- 내용

[Fix] load_chat_history 수정

---

main.py
src/retrieval/retrieval.py
src/retrieval/retrieval_main.py

- 리트리버에 chat_history 인자로 반영
- 내용

[Refactor] chat_history 인자로 반영

---

src/streamlit/chatbot.py

[Fix] chat_history가 두번 선언되어있는 문제 수정

---

backend/chatbot_original.py
backend/main.py
src/streamlit/chatbot.py

- fastAPI 연동 완료
- Notion 회의록 > 13차 회의 > 배포 코드 설명 페이지에 자세한 설명을 적어두었습니다.
- X

[Fix] fastAPI 연동 완료

---

README.md

[Fix] readme

---

backend/chatbot_original.py
backend/main.py
main.py
src/embedding/embedding_main.py
src/streamlit/chatbot.py

- 각 세션마다 고유 ID 부여 및 DB 또한 분할하여 충돌방지
- Chatbot 을 구동하는 로직이 꼬여서 FastAPI를 실행하는 방법 말고는 실행할수 없다.

[Fix] uuid 적용

---

src/utils/config.py

[Fix] 백에서 verbose 출력 주석 처리

---

README.md

[Fix] 협업일지 링크 오류 수정
- 협업일지 링크 오류 수정
- X

[Fix] 협업일지 링크 오류 수정

---

README.md

[Fix] 리드미 수정
